default language config
MakinoharaShoko/WebGAL pull request #368
Opened 2023-09-02 04:46 UTC by hshqwq

2023-09-02 14:36 UTC, MakinoharaShoko commented
runtime 下的 etc.ts 应该在某次重构中删除了，应当排查一下它为何又出现了。同步现有分支的时候有出现问题？

2023-09-02 14:51 UTC, hshqwq commented
哦，应该是我处理合并冲突时被保留了，毕竟我上次更改是3个月前了，同步时可能正好有修改在里面被保留了

2023-09-02 16:29 UTC, MakinoharaShoko requested changes
在用户数据中，我们保存了有关选择语言的相关信息。我认为应该将语言信息存储在用户数据中，而不是在 store 中新建一个 lang 字段，原因如下：
1、这样每个游戏可以对应一个默认语言
2、减少 store 中 key 的数目，降低管理复杂度，用户数据只需要在一个地方存就够了

2023-09-03 15:55 UTC, MakinoharaShoko commented
貌似之前判断语言的初始化方式是通过 localStorage 中的一个值判断的，虽然我打算改成也放到用户存储数据中，但这样可能会导致一些异步的问题，因为：
1、游戏信息获取之后，才知道key是什么，才能去获取用户数据，才能去知道语言有没有初始化
2、语言初始化的选择是一开始就会显示的，假如在游戏key还没有找到的时候，就去选择这个选项会怎么样（会存入一个key为空串的用户数据中）
3、选择的时候没有加载用户选项，选择后加载了，用户会不会觉得，我明明选择了英语，结果出来了中文
4、已经选择语言的用户，会疑惑为啥又出现了语言的选项
所以，也许把语言放在 localStorage 中，然后每次更新语言设置的时候，localStorage 和带 key  的用户数据都改，才是正确的方案，这好像也是我们现行的方案。
不知道你有没有其他的方案

2023-09-05 09:04 UTC, MakinoharaShoko commented
想到了一个更好的解决方案
## 原则
监听 userData 这个 reducer 中的 language 字段，当这里改变的时候，一定会修改界面语言和 localStorage 中的 lang 条目。
## 当第一次加载时
1、这时 lang 未设置，userData 未设置，弹出选择语言选项
2、获取了 config.txt，这时候可能有 defaultLanguage。假如有 defaultLanguage，检查 userData 中有没有设置 lang，如果有，则什么也不做（由于是第一次加载，所以应当没有），如果无，则修改该字段。由于我们监听了这个字段，所以界面语言和 localStorage 中的 lang 一定会更新。
## 当后续加载时
1、lang 设置了，所以不显示语言选项
2、获取了 config.txt，获取了 userData，由于已经设置过，所以什么也不做
3、但是假如 lang 中的条目和 userData 冲突了怎么办？以 userData 为准（考虑到用户导入导出存档的情况，所以我们的一切设置都以 userData 为准）
## useTranslation 初始化时，由于 userData 是异步获取的，所以初始化时以什么为准？
以 lang 为准，没有则显示选择语言界面。（当然，如果我们在 config.txt 中设置了默认语言，这个界面可能闪一下就消失了，还好我们设置了落地页，大多数情况下用户来不及看到这个界面）

2023-09-16 16:34 UTC, closed without merging